### ISSUE TITLE
Android compile

### ISSUE THREAD

**Issue by Kahllo** [vfsfitvnm/intruducer#1]
Cant compile for android 

cargo build --example introduced --target aarch64-linux-android 

![Capture1](https://github.com/vfsfitvnm/intruducer/assets/74785129/2e0d9617-98ee-4032-9249-bd8df6842ff1)

cargo ndk -t aarch64-linux-android build 

![Capture](https://github.com/vfsfitvnm/intruducer/assets/74785129/c9ed6e63-1b41-463f-b662-7afaf54fe610)

![Capture3](https://github.com/vfsfitvnm/intruducer/assets/74785129/6026fe8f-3c89-4aa0-98b0-e4645d060a0a)

**Comment by vfsfitvnm** [comment]
I don't know how `cargo-ndk` works, but this is how I can successfully compile:
```sh
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=~/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
cargo build --example intruducer --target aarch64-linux-android
```

**Comment by Kahllo** [comment]
Thanks, is worked !! :)
