### ISSUE TITLE
Is it possible to load environment variables used by the library?

### ISSUE THREAD

**Issue by przemyslaw0** [vfsfitvnm/intruducer#3]
I would like to inject a library in my stuff but this library relies on envonment variable to work.

Is it possible to pass environment variables to the library injected (or maybe the tricked application)?

**Comment by vfsfitvnm** [comment]
Nope. I guess you can first inject a library created by you to set the environment variables you need, and then inject the target library.

**Comment by przemyslaw0** [comment]
@vfsfitvnm 

I tried to hack around: https://paste.ee/p/T5UGe

But it doesn't seem to work. Any help welcome!

**Comment by przemyslaw0** [comment]
I found a program that do something similar to intruducer, but directly in the executable file: https://github.com/elfmaster/dt_infect

It work with some libraries, libraries that intercept bind() and connect() in the program doesn't with dt_infect.

Thanks.
